<?
$_pages = array(
'27'=>'newsletter.php',
'22'=>'galleries.php',
'21'=>'giftcards.php',
'20'=>'news.php',
'19'=>'usrpass.php',
'18'=>'failure.php',
'17'=>'event.php',
'16'=>'success.php',
//'15'=>'terms.php',
'14'=>'register.php',
'13'=>'usefull.php',
'12'=>'static pages',
'11'=>'login.php',
'10'=>'wineclub.php',
'9'=>'wineries.php',
'8'=>'services.php',
'7'=>'profile.php',
'6'=>'address.php',
'5'=>'order.php',
'4'=>'basket.php',
'3'=>'view.php',
'2'=>'search.php',
'1'=>'index.php',

'0'=>'', // Global page

'-1'=>'admin/home.php',
'-3'=>'admin/profile.php',
'-4'=>'admin/users.php',

'-5'=>'admin/nom_product_types.php',
'-6'=>'admin/nom_product_sizes.php',
'-7'=>'admin/nom_producers.php',
'-8'=>'admin/nom_vintages.php',
'-9'=>'admin/nom_wine_types.php',
'-10'=>'admin/nom_wine_sorts.php',
'-11'=>'admin/nom_unit_types.php',
'-12'=>'admin/nom_bottle_types.php',
'-13'=>'admin/partners.php',
'-14'=>'admin/restaurants.php',
'-15'=>'admin/products.php',
'-16'=>'admin/nom_countries.php',
'-17'=>'admin/promotions.php',
'-18'=>'admin/nom_someliers.php',
'-19'=>'admin/nom_country_groups.php',
'-20'=>'admin/product_outfits.php',

'-21'=>'admin/library.php',
'-22'=>'admin/image.php',
'-23'=>'admin/nom_assessments.php',
'-24'=>'admin/addressess.php',
'-25'=>'admin/orders.php',
'-26'=>'admin/nom_user_types.php',
'-27'=>'admin/log.php',
'-28'=>'admin/bulletin.php',
'-29'=>'admin/system.php',
'-30'=>'admin/archive.php',
'-31'=>'admin/quiz.php',
'-32'=>'admin/answers.php',
'-33'=>'admin/resultmap.php',

'-34'=>'admin/nom_product_colors.php',
'-35'=>'admin/nom_wine_price_ranges.php',
'-36'=>'admin/nom_wine_strength_ranges.php',
'-37'=>'admin/nom_wine_maturity.php',
'-38'=>'admin/settings.php',
'-39'=>'admin/del_zones.php',
'-40'=>'admin/popular_searches.php',
'-41'=>'admin/reports.php',
'-42'=>'admin/galleries.php',
);
?>